"""Certificate management routes."""

import datetime
import glob
import json
import os
import shlex
import shutil
import subprocess
import time
import uuid
import zipfile
from io import BytesIO
from threading import Thread

from flask import Blueprint, Response, jsonify, request, send_file
from jinja2 import Environment, FileSystemLoader, TemplateNotFound

from config import cfg
from utils.metrics import CERT_DEPLOYS
from .audit import audit_log
from .shared import (
    ALLOWED_CERT_FILES,
    CERT_DOMAINS,
    PLAYBOOK_DIR,
    PLAYBOOK_TEMPLATE_DIR,
    ROOT_DIR,
    SUBPROCESS_TIMEOUT,
    api_error,
    cert_sessions,
    get_vthunder_host_credentials,
    is_safe_filename,
)
from .system_bp import _get_vthunder_certs

certificates_bp = Blueprint("certificates", __name__)

# Jinja2 environment for playbook templates (custom delimiters to avoid Ansible conflicts)
jinja_env = Environment(
    loader=FileSystemLoader(PLAYBOOK_TEMPLATE_DIR),
    variable_start_string='[[',
    variable_end_string=']]',
    comment_start_string='[#',
    comment_end_string='#]',
)


# ── Helpers ─────────────────────────────────────────────────

def find_cert_fullchain(cert_path):
    """Find fullchain.pem in various possible locations.

    Checks live/ first (certbot's canonical location for current certs),
    then falls back to root-level files (legacy/non-certbot layouts).
    """
    live_pattern = os.path.join(cert_path, "live", "*", "fullchain.pem")
    live_certs = glob.glob(live_pattern)
    if live_certs:
        return max(live_certs, key=os.path.getmtime)
    direct_pattern = os.path.join(cert_path, "fullchain*.pem")
    direct_certs = [f for f in glob.glob(direct_pattern) if os.path.isfile(f)]
    if direct_certs:
        return max(direct_certs, key=os.path.getmtime)
    return None


def _resolve_cert_path(base_domain, name, filename):
    """Resolve cert file path with security validation."""
    if base_domain not in CERT_DOMAINS:
        return None, "Invalid base domain", 400
    if filename not in ALLOWED_CERT_FILES:
        return None, "File not allowed", 400
    if ".." in name or "/" in name:
        return None, "Invalid cert name", 400
    cert_dir = CERT_DOMAINS[base_domain]["cert_path"]
    file_path = os.path.join(cert_dir, "live", name, filename)
    real = os.path.realpath(file_path)
    if not real.startswith(os.path.realpath(cert_dir)):
        return None, "Path traversal blocked", 400
    if not os.path.isfile(real):
        return None, "File not found", 404
    return real, None, None


def generate_cert_playbook(base_domain, domains, cert_path):
    """Generate Ansible playbook YAML for certificate deployment."""
    playbook = f"""---
# Ansible Playbook: Deploy SSL Certificate for {base_domain}
# Generated by Q Branch Automation Demo
# Domains: {', '.join(domains)}

- name: Deploy SSL Certificate - {base_domain}
  hosts: all
  become: yes
  vars:
    cert_source_path: "{cert_path}"
    cert_dest_path: "/etc/ssl/certs"
    key_dest_path: "/etc/ssl/private"

  tasks:
    - name: Ensure SSL directories exist
      file:
        path: "{{{{ item }}}}"
        state: directory
        mode: '0755'
      loop:
        - "{{{{ cert_dest_path }}}}"
        - "{{{{ key_dest_path }}}}"

    - name: Copy fullchain certificate
      copy:
        src: "{{{{ cert_source_path }}}}/fullchain.pem"
        dest: "{{{{ cert_dest_path }}}}/{base_domain}-fullchain.pem"
        mode: '0644'
        owner: root
        group: root
      notify: Reload web service

    - name: Copy private key
      copy:
        src: "{{{{ cert_source_path }}}}/privkey.pem"
        dest: "{{{{ key_dest_path }}}}/{base_domain}-privkey.pem"
        mode: '0600'
        owner: root
        group: root
      notify: Reload web service

  handlers:
    - name: Reload web service
      service:
        name: nginx  # Change to your web server (apache2, httpd, etc.)
        state: reloaded
"""
    return playbook


# ── Routes ──────────────────────────────────────────────────

@certificates_bp.route("/api/cert/domains", methods=["GET"])
def cert_list_domains():
    domains = []
    for domain, config in CERT_DOMAINS.items():
        cert_info = {
            "domain": domain, "has_cert": False,
            "expires": None, "status": "none", "cert_count": 0,
        }
        cert_path = config["cert_path"]
        live_dir = os.path.join(cert_path, "live")
        if os.path.isdir(live_dir):
            cert_dirs = [d for d in os.listdir(live_dir)
                         if os.path.isdir(os.path.join(live_dir, d)) and d != "README"]
            cert_info["cert_count"] = len(cert_dirs)

        fullchain_path = find_cert_fullchain(cert_path)
        if fullchain_path:
            cert_info["has_cert"] = True
            cert_info["status"] = "valid"
            if cert_info["cert_count"] == 0:
                cert_info["cert_count"] = 1
            try:
                result = subprocess.run(
                    ["openssl", "x509", "-enddate", "-noout", "-in", fullchain_path],
                    capture_output=True, text=True, timeout=5,
                )
                if result.returncode == 0 and "notAfter=" in result.stdout:
                    cert_info["expires"] = result.stdout.strip().split("notAfter=")[1]
            except Exception:
                pass
        domains.append(cert_info)
    return jsonify({"domains": domains})


@certificates_bp.route("/api/cert/domains/detail", methods=["GET"])
def cert_list_domains_detail():
    result = []
    for domain, config in CERT_DOMAINS.items():
        cert_path = config["cert_path"]
        certs = []
        live_dir = os.path.join(cert_path, "live")
        if os.path.isdir(live_dir):
            for entry in sorted(os.listdir(live_dir)):
                sub_path = os.path.join(live_dir, entry)
                if os.path.isdir(sub_path) and entry != "README":
                    fc = os.path.join(sub_path, "fullchain.pem")
                    if os.path.isfile(fc):
                        certs.append((entry, fc))
        else:
            for fc in sorted(glob.glob(os.path.join(cert_path, "fullchain*.pem"))):
                if os.path.isfile(fc):
                    certs.append((domain, fc))
                    break

        cert_details = []
        for name, fc_path in certs:
            info = {"name": name, "expires": None, "issued": None,
                    "days_remaining": None, "status": "unknown",
                    "serial": None, "issuer": None}
            try:
                out = subprocess.run(
                    ["openssl", "x509", "-noout",
                     "-enddate", "-startdate", "-serial", "-issuer",
                     "-in", fc_path],
                    capture_output=True, text=True, timeout=5,
                )
                if out.returncode == 0:
                    for line in out.stdout.strip().splitlines():
                        if line.startswith("notAfter="):
                            info["expires"] = line.split("=", 1)[1]
                        elif line.startswith("notBefore="):
                            info["issued"] = line.split("=", 1)[1]
                        elif line.startswith("serial="):
                            info["serial"] = line.split("=", 1)[1]
                        elif line.startswith("issuer="):
                            info["issuer"] = line.split("=", 1)[1].strip()
                    if info["expires"]:
                        try:
                            exp_dt = datetime.datetime.strptime(
                                info["expires"], "%b %d %H:%M:%S %Y %Z"
                            ).replace(tzinfo=datetime.timezone.utc)
                            now = datetime.datetime.now(datetime.timezone.utc)
                            info["days_remaining"] = (exp_dt - now).days
                            if info["days_remaining"] < 0:
                                info["status"] = "expired"
                            elif info["days_remaining"] < 7:
                                info["status"] = "critical"
                            elif info["days_remaining"] < 30:
                                info["status"] = "expiring_soon"
                            else:
                                info["status"] = "valid"
                        except ValueError:
                            pass
            except Exception:
                pass
            cert_details.append(info)

        total = len(cert_details)
        valid = sum(1 for c in cert_details if c["status"] == "valid")
        expiring = sum(1 for c in cert_details if c["status"] in ("expiring_soon", "critical"))
        days_list = [c["days_remaining"] for c in cert_details if c["days_remaining"] is not None]
        earliest_days = min(days_list) if days_list else None
        earliest_expiry = None
        if earliest_days is not None:
            for c in cert_details:
                if c["days_remaining"] == earliest_days:
                    earliest_expiry = c["expires"]
                    break

        result.append({
            "domain": domain, "certs": cert_details,
            "summary": {
                "total": total, "valid": valid, "expiring_soon": expiring,
                "earliest_expiry": earliest_expiry, "earliest_days": earliest_days,
            },
        })
    return jsonify({"domains": result})


@certificates_bp.route("/api/cert/view", methods=["GET"])
def cert_view_file():
    base_domain = request.args.get("base_domain", "")
    name = request.args.get("name", "")
    filename = request.args.get("file", "fullchain.pem")
    path, error, status = _resolve_cert_path(base_domain, name, filename)
    if error:
        return api_error(error, status)
    with open(path, "r") as f:
        content = f.read()
    return jsonify({"content": content, "file": filename, "name": name})


@certificates_bp.route("/api/cert/download", methods=["GET"])
def cert_download_file():
    base_domain = request.args.get("base_domain", "")
    name = request.args.get("name", "")
    filename = request.args.get("file", "fullchain.pem")
    path, error, status = _resolve_cert_path(base_domain, name, filename)
    if error:
        return api_error(error, status)
    download_name = f"{name}_{filename}"
    return send_file(path, as_attachment=True, download_name=download_name,
                     mimetype="application/x-pem-file")


@certificates_bp.route("/api/cert/download-all", methods=["GET"])
def cert_download_all():
    base_domain = request.args.get("base_domain", "")
    name = request.args.get("name", "")
    if base_domain not in CERT_DOMAINS:
        return api_error("Invalid base domain")
    if ".." in name or "/" in name:
        return api_error("Invalid cert name")
    cert_dir = CERT_DOMAINS[base_domain]["cert_path"]
    live_dir = os.path.join(cert_dir, "live", name)
    real_live = os.path.realpath(live_dir)
    if not real_live.startswith(os.path.realpath(cert_dir)):
        return api_error("Path traversal blocked")

    buf = BytesIO()
    added = 0
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for filename in ALLOWED_CERT_FILES:
            file_path = os.path.join(live_dir, filename)
            real = os.path.realpath(file_path)
            if not real.startswith(os.path.realpath(cert_dir)):
                continue
            if os.path.isfile(real):
                zf.write(real, filename)
                added += 1
    if added == 0:
        return api_error("No cert files found", 404)
    buf.seek(0)
    return send_file(buf, as_attachment=True, download_name=f"{name}_certs.zip",
                     mimetype="application/zip")


@certificates_bp.route("/api/cert/delete", methods=["POST"])
def cert_delete():
    """Delete a certificate using certbot delete via docker compose."""
    data = request.json or {}
    base_domain = data.get("base_domain", "")
    name = data.get("name", "")

    if not base_domain or base_domain not in CERT_DOMAINS:
        return api_error("Invalid base domain")
    if not name or ".." in name or "/" in name:
        return api_error("Invalid cert name")

    config = CERT_DOMAINS[base_domain]

    # Verify the cert actually exists before trying to delete
    cert_dir = config["cert_path"]
    live_dir = os.path.join(cert_dir, "live", name)
    if not os.path.isdir(live_dir):
        return api_error(f"Certificate '{name}' not found", 404)

    audit_log("cert_delete", base_domain, f"cert_name={name}")

    compose_cmd = [
        "docker", "compose",
        "-f", os.path.join(config["compose_dir"], "docker-compose.yml"),
        "run", "--quiet-pull", "--rm", config["service"],
        "delete", "--cert-name", name, "--non-interactive",
    ]

    try:
        proc = subprocess.run(
            compose_cmd,
            capture_output=True,
            text=True,
            timeout=60,
        )
    except subprocess.TimeoutExpired:
        return api_error("certbot delete timed out", 504)

    if proc.returncode != 0:
        return api_error(
            f"certbot delete failed (exit {proc.returncode}): {proc.stderr.strip() or proc.stdout.strip()}",
            500,
        )

    return jsonify({
        "success": True,
        "message": f"Certificate '{name}' deleted from {base_domain}",
    })


@certificates_bp.route("/api/cert/info", methods=["GET"])
def cert_get_info():
    domain = request.args.get("domain")
    if not domain or domain not in CERT_DOMAINS:
        return api_error("Invalid domain")
    config = CERT_DOMAINS[domain]
    fullchain_path = find_cert_fullchain(config["cert_path"])
    if not fullchain_path:
        return jsonify({"domain": domain, "exists": False, "status": "No certificate found"})

    cert_details = {
        "domain": domain, "exists": True, "status": "Valid",
        "expires": None, "issued": None, "serial": None, "issuer": None,
    }
    try:
        for flag, key, prefix in [
            ("-enddate", "expires", "notAfter="),
            ("-startdate", "issued", "notBefore="),
            ("-serial", "serial", "serial="),
            ("-issuer", "issuer", "issuer="),
        ]:
            result = subprocess.run(
                ["openssl", "x509", flag, "-noout", "-in", fullchain_path],
                capture_output=True, text=True, timeout=5,
            )
            if result.returncode == 0 and prefix in result.stdout:
                cert_details[key] = result.stdout.strip().split(prefix)[1]
    except Exception:
        pass
    return jsonify(cert_details)


@certificates_bp.route("/api/cert/execute", methods=["POST"])
def cert_execute():
    data = request.json
    base_domain = data.get("base_domain")
    common_name = data.get("common_name", "").strip()
    wildcard = data.get("wildcard", False)
    sans = data.get("sans", "").strip()
    action = data.get("action", "obtain")
    email = data.get("email", cfg.CERTBOT_EMAIL)
    environment = data.get("environment", "production")
    dry_run = data.get("dry_run", False)
    create_playbook = data.get("create_playbook", False)
    playbook_name = data.get("playbook_name", "")
    extra_flags = data.get("extra_flags", "").strip()

    if not base_domain or base_domain not in CERT_DOMAINS:
        return api_error("Invalid domain")

    config = CERT_DOMAINS[base_domain]
    session_id = str(uuid.uuid4())

    domains = []
    if wildcard:
        cn = f"*.{base_domain}"
    elif common_name:
        cn = f"{common_name}.{base_domain}"
    else:
        cn = base_domain
    domains.append(cn)

    if sans:
        for san in [s.strip() for s in sans.split(",") if s.strip()]:
            full_san = f"{san}.{base_domain}"
            if full_san not in domains:
                domains.append(full_san)

    cred_file_map = {
        "valowgaming.com": "/certbot-valowgaming.ini",
        "sinkscanyon.net": "/certbot-sinkscanyon.ini",
        "klouda.co": "/certbot-klouda-co.ini",
        "klouda.work": "/certbot-klouda-work.ini",
    }
    cred_file = cred_file_map.get(base_domain, "/cloudflare.ini")

    cert_args = ["certonly", "--dns-cloudflare", "--dns-cloudflare-credentials", cred_file]
    for d in domains:
        cert_args.extend(["-d", d])
    cert_args.extend(["--cert-name", domains[0]])
    cert_args.extend(["--email", email, "--agree-tos", "--non-interactive"])

    if action in ("renew", "force-renew"):
        cert_args.append("--force-renewal")
    if action == "revoke":
        cert_args = ["revoke", "--non-interactive", "--cert-path",
                     f"/etc/letsencrypt/live/{base_domain}/fullchain.pem"]
    if environment == "staging":
        cert_args.append("--staging")
    if dry_run:
        cert_args.append("--dry-run")
    if extra_flags:
        try:
            cert_args.extend(shlex.split(extra_flags))
        except ValueError:
            cert_args.append(extra_flags)

    audit_log("cert_execute", base_domain, f"action={action} domains={','.join(domains)} dry_run={dry_run}")

    cert_sessions[session_id] = {
        "domain": base_domain, "domains": domains, "action": action,
        "output": [], "status": "running", "start_time": time.time(),
    }

    def run_certbot():
        try:
            cert_sessions[session_id]["output"].append("Preparing Certbot container (pulling image if needed)...")
            compose_cmd = [
                "docker", "compose",
                "-f", os.path.join(config["compose_dir"], "docker-compose.yml"),
                "run", "--quiet-pull", "--rm", config["service"],
            ] + cert_args

            process = subprocess.Popen(
                compose_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                text=True, bufsize=1,
            )
            for line in process.stdout:
                cert_sessions[session_id]["output"].append(line.rstrip())
            try:
                process.wait(timeout=SUBPROCESS_TIMEOUT)
            except subprocess.TimeoutExpired:
                process.kill()
                cert_sessions[session_id]["status"] = "failed"
                cert_sessions[session_id]["output"].append(
                    f"\n❌ Process killed after {SUBPROCESS_TIMEOUT}s timeout"
                )
                return

            if process.returncode == 0:
                cert_sessions[session_id]["status"] = "completed"
                cert_sessions[session_id]["output"].append("\n✅ Certificate operation completed successfully!")
                if create_playbook and playbook_name:
                    playbook_path = os.path.join(PLAYBOOK_DIR, playbook_name)
                    playbook_content = generate_cert_playbook(base_domain, domains, config["cert_path"])
                    with open(playbook_path, "w") as f:
                        f.write(playbook_content)
                    cert_sessions[session_id]["output"].append(f"\n📄 Ansible playbook created: {playbook_path}")
            else:
                cert_sessions[session_id]["status"] = "failed"
                cert_sessions[session_id]["output"].append(
                    f"\n❌ Certificate operation failed with exit code {process.returncode}"
                )
        except Exception as e:
            cert_sessions[session_id]["status"] = "error"
            cert_sessions[session_id]["output"].append(f"\n❌ Error: {str(e)}")

    thread = Thread(target=run_certbot, daemon=True)
    thread.start()

    return jsonify({"session_id": session_id, "message": "Certificate operation started", "domains": domains})


@certificates_bp.route("/api/cert/stream/<session_id>")
def cert_stream(session_id):
    def generate():
        if session_id not in cert_sessions:
            yield f"data: {json.dumps({'error': 'Invalid session ID'})}\n\n"
            return
        session = cert_sessions[session_id]
        last_line = 0
        while True:
            current_output = session["output"]
            if len(current_output) > last_line:
                for line in current_output[last_line:]:
                    yield f"data: {json.dumps({'line': line})}\n\n"
                last_line = len(current_output)
            if session["status"] in ["completed", "failed", "error"]:
                yield f"data: {json.dumps({'status': session['status'], 'done': True})}\n\n"
                break
            time.sleep(0.5)
    return Response(generate(), mimetype="text/event-stream")


@certificates_bp.route("/api/cert/generate_playbook", methods=["POST"])
def api_generate_cert_playbook():
    from .shared import is_safe_filename

    data = request.json or {}
    domain = data.get("domain", "").strip()
    target_type = data.get("target_type", "").strip()
    playbook_name = data.get("playbook_name", "").strip()
    partition = data.get("partition", "").strip()
    vthunder_host = data.get("vthunder_host", "").strip()

    if not domain:
        return api_error("Domain is required")

    valid_target_types = ["linux_wildcard", "linux_common_name", "vthunder_vip"]
    if target_type not in valid_target_types:
        return api_error(f"Invalid target_type. Must be one of: {', '.join(valid_target_types)}")

    if target_type == "vthunder_vip":
        if not partition:
            return api_error("partition is required for vthunder_vip target type")
        if not vthunder_host:
            return api_error("vthunder_host is required for vthunder_vip target type")

    if not playbook_name:
        safe_domain = domain.replace("*", "wildcard").replace(".", "_")
        playbook_name = f"deploy_cert_{safe_domain}.yml"

    if not is_safe_filename(playbook_name):
        return api_error("Invalid playbook filename")
    if not playbook_name.endswith((".yml", ".yaml")):
        playbook_name += ".yml"

    template_map = {
        "linux_wildcard": "linux_wildcard.yml.j2",
        "linux_common_name": "linux_common_name.yml.j2",
        "vthunder_vip": "vthunder_vip.yml.j2",
    }

    try:
        template = jinja_env.get_template(template_map[target_type])
    except TemplateNotFound:
        return api_error(f"Template not found: {template_map[target_type]}", 500)

    import datetime as dt
    cert_name = domain.replace("*", "wildcard").replace(".", "_")
    template_vars = {"domain": domain, "cert_name": cert_name, "timestamp": dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
    if target_type == "vthunder_vip":
        template_vars["partition"] = partition
        template_vars["vthunder_host"] = vthunder_host

    try:
        playbook_content = template.render(**template_vars)
    except Exception as e:
        return api_error(f"Template rendering failed: {str(e)}", 500)

    playbook_path = os.path.join(PLAYBOOK_DIR, playbook_name)
    real_playbook_dir = os.path.realpath(PLAYBOOK_DIR)
    if not os.path.realpath(playbook_path).startswith(real_playbook_dir):
        return api_error("Invalid playbook path", 403)

    archived_file = None
    if os.path.exists(playbook_path):
        archive_dir = os.path.join(PLAYBOOK_DIR, "_archive")
        os.makedirs(archive_dir, exist_ok=True)
        archive_timestamp = dt.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        archive_name = f"{os.path.splitext(playbook_name)[0]}_{archive_timestamp}.yml"
        archive_path = os.path.join(archive_dir, archive_name)
        try:
            shutil.move(playbook_path, archive_path)
            archived_file = archive_name
        except Exception:
            pass

    try:
        with open(playbook_path, 'w') as f:
            f.write(playbook_content)
    except Exception as e:
        return api_error(f"Failed to write playbook: {str(e)}", 500)

    audit_log("cert_playbook_generate", playbook_name, f"domain={domain} target={target_type}")

    message = f"Playbook '{playbook_name}' created successfully"
    if archived_file:
        message += f" (previous version archived as '{archived_file}')"

    return jsonify({
        "success": True, "playbook": playbook_name, "path": playbook_path,
        "target_type": target_type, "archived": archived_file, "message": message,
    })


# ── vThunder Cert Deployment ──────────────────────────────

@certificates_bp.route("/api/cert/deploy-vthunder", methods=["POST"])
def api_cert_deploy_vthunder():
    """Deploy a certificate directly to a vThunder device."""
    data = request.json or {}
    base_domain = data.get("base_domain", "").strip()
    domain = data.get("domain", "").strip()
    cert_file = data.get("cert_file", "fullchain.pem").strip()
    vthunder_host = data.get("vthunder_host", "").strip()
    vthunder_group = data.get("vthunder_group", "").strip()
    partition = data.get("partition", "").strip()

    if not all([base_domain, domain, vthunder_host, vthunder_group, partition]):
        return api_error("base_domain, domain, vthunder_host, vthunder_group, and partition are required")

    # Validate cert file
    if cert_file not in ("fullchain.pem", "cert.pem"):
        return api_error("cert_file must be fullchain.pem or cert.pem")

    # Resolve cert path
    cert_path, err, status = _resolve_cert_path(base_domain, domain, cert_file)
    if err:
        return api_error(err, status)
    key_path, err, status = _resolve_cert_path(base_domain, domain, "privkey.pem")
    if err:
        return api_error(f"Private key not found: {err}", status)

    # Resolve vThunder credentials from inventory
    creds = get_vthunder_host_credentials("inventory.yml", vthunder_group, vthunder_host)
    if not creds:
        return api_error(f"Could not find credentials for {vthunder_host} in {vthunder_group}")

    # Derive cert name
    cert_name = domain.replace(".", "_").replace("*", "wildcard")

    # Check if cert already exists on device (renewal detection)
    is_renewal = False
    try:
        existing_certs = _get_vthunder_certs(
            host=vthunder_host, username=creds["username"],
            password=creds["password"], partition=partition, port=creds["port"],
        )
        existing_names = [c.get("file", "") for c in existing_certs]
        is_renewal = any(cert_name in name for name in existing_names)
    except Exception:
        pass  # Non-fatal — we'll still attempt the upload

    # Run upload helper
    helper = os.path.join(ROOT_DIR, "python", "helpers", "upload_cert_to_vthunder.py")
    cmd = [
        "python3", helper,
        "--host", vthunder_host,
        "--port", str(creds["port"]),
        "--username", creds["username"],
        "--password", creds["password"],
        "--partition", partition,
        "--cert-name", cert_name,
        "--cert-file", cert_path,
        "--key-file", key_path,
    ]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60,
                                cwd=os.path.join(ROOT_DIR, "python"))
        output_lines = result.stdout.strip().split("\n") if result.stdout else []
        success = result.returncode == 0
        CERT_DEPLOYS.labels(status="success" if success else "failed").inc()

        action = "renewed" if is_renewal else "deployed"
        audit_log("cert_deploy_vthunder", f"{cert_name} → {vthunder_host}/{partition}",
                  f"domain={domain} action={action} success={success}")

        if success:
            return jsonify({
                "success": True,
                "cert_name": cert_name,
                "is_renewal": is_renewal,
                "message": f"Certificate '{cert_name}' {'renewed' if is_renewal else 'deployed'} on {vthunder_host}/{partition}",
                "output": output_lines,
            })
        else:
            err_detail = result.stderr.strip() or result.stdout.strip() or 'Unknown error'
            return api_error(
                f"Upload failed: {err_detail}",
                500,
            )
    except subprocess.TimeoutExpired:
        return api_error("Upload timed out after 60 seconds", 504)
    except Exception as e:
        return api_error(str(e), 500)
